### ISSUE TITLE
hwh doesn't respect [tool.setuptools] directives

### ISSUE THREAD

**Issue by mkgessen** [mkgessen/hwh-backend#4]
HWH should still support standard setuptools directives in pyproject.toml

The user should be able to do things like
```toml
[tool.setuptools]
packages = ["my_project"]
package-dir = {"" = "src"}
```

Later, it might be nices to replicate the behaviour to
```toml
[tool.hwh]
packages = ["my_project"]
package-dir = {"" = "src"}
```
but let's start by supporting standard setuptools stuff. Makes migration easier
